@startuml
class Ticket{









}

class Seat{








}

class Customer{
}

class Movie{
}

class Payment{
}

class Cinnamon{
}

class TheatreRoom{
}

enum Row{







}

Customer -right- Cinnamon
TheatreRoom -- Seat
Seat -- Row
Cinnamon -down- Payment
Cinnamon -up- Ticket
Cinnamon -right- TheatreRoom
TheatreRoom -up- Movie

@enduml